version: '3'
services:
  mongoDatabase:
    image: 'mongo:5.0'
    volumes:
      - /data/db:/data/db
    
  app:
    build: ./
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
    ports:
      - '4000:4000'
    volumes:
      - ./:/usr/node_app
